
server:
  port: 8192

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shopping_mall
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 3478
  jpa:
    hibernate:
      ddl-auto: create #update #create #none #jpa테이블자동생성
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

